### ISSUE TITLE
re-implement alluvial() ggplot-style

### ISSUE THREAD

**Issue by mbojan** [mbojan/alluvial#10]
Customization will be easier if whole plot is re-implemented in `grid` or `ggplot`, i.e., a plot is completely described with some R object which is plotted afterwards

**Comment by mbojan** [comment]
The question is how to translate this plot into Grammar-of-graphics style API so that #16 will be easier.

**Comment by mbojan** [comment]
https://github.com/corybrunson/ggalluvial

**Comment by corybrunson** [comment]
It turns out that #16 (this auto-completed so i'm thinking it might auto-hyperlink, too) is also awkward in the ggplot setup—not because it's difficult for a `geom_*()` to handle them separately, but because it's hard to know how to include them in `aes()` call, when: the number of values is several times the number of rows in the dataset, and ggplot2 expects the data to be "tidy", i.e. one observation (in this case, one flow) per row.

**Comment by mbojan** [comment]
I think the main "difficulty" is that even though the aesthetics of the flows are functions of original data, the are hardly ever simple identities (even having `scale_*` in between). IMHO color more often used as a sort of annotation tool duplicating information that is already there (as a combination of values of axes already on the diagram).

Easy case are ribbon colors that are to be applied throughout:  they are usually just a function of variable values (e.g. `Sex=="Female" & !Survived`). Not so easy case is in the panel data context (axes corresponding to waves) as you might want to use different colors depending on the period.

Nevertheless it would be great to come up with something clean. Quite some people emailed me asking how to color individual segments. At this moment mostly hacks come to my mind, and it is far more easy to hack base graphics rather than `ggplot2`, which is based on `grid`...

**Comment by corybrunson** [comment]
I agree that this makes more sense in the panel setting, where one might want to, e.g., have `alpha` increase from left to right. And i think this would be easy to do in the ggplot2 setting, if the diagram were called via, e.g., `aes(x = time, y = group)`. I'll make a point to try this too.

In the original setting, though, would it even be appropriate to make this work? Wilkinson writes in *The Grammar of Graphics*, "This system is capable of producing some hideous graphics. ... This system cannot produce a meaningless graphic, however." I need to read more of the book, but i wonder if this is the kind of thing ggplot2 was designed to make difficult.

**Comment by mbojan** [comment]
See https://github.com/corybrunson/ggalluvial
