### ISSUE TITLE
Issue installing on 3.2.2

### ISSUE THREAD

**Issue by churi15** [mbojan/alluvial#12]
Hi Michal
i have the following issue installing on R 3.2.2
> library(devtools)
> install_github("mbojan/alluvial")
Downloading GitHub repo mbojan/alluvial@master
Installing alluvial
"//C13F36/BB9119$/DOCUME~1/R/R-32~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/BB9119/AppData/Local/Temp/RtmpgdY4SI/devtools1508152324e4/mbojan-alluvial-a83b219"  \
  --library="\\C13F36/BB9119$/Documents/R/R-3.2.2/library" --install-tests 

'\\C13F36\BB9119$\DOCUME~1\R\R-32~1.2' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)
> install.packages("alluvial")
Warning in install.packages :
  package ‘alluvial’ is not available (for R version 3.2.2)

Thanks in advance!

Uriel

**Comment by mbojan** [comment]
This looks like a more general issue with your R/RStudio installation rather than something specific to alluvial. Did you try installing some other package with `install_github`?

**Comment by churi15** [comment]
Hi Michal
you are right, It seems to be the same with other packages, i am trying to fix it with no sucess. if you have any ideas, much appreciated.
Uriel

**Comment by mbojan** [comment]
I think for some reason `devtools::install_github` constructs an erroneous command to install the package. In particular the path to R executable seems not correct. I assume that RStudio works in general (?). Perhaps R is installed in some awkward location and/or path contains spaces or some strange characters? It's hard for me to say... Perhaps reinstalling R and/or RStudio would solve the problem.

I suggest you try your luck on stackoverflow.com or RStudio support.
