### ISSUE TITLE
Alluvial from two tables

### ISSUE THREAD

**Issue by dvictori** [mbojan/alluvial#13]
Not sure this is the right place to ask but here goes. First, thanks for developing this package. I've been able to create some nice graphs. But now I'm stuck. I'm working with landcover maps for 3 dates (2000, 2010 and 2012) and I'd like to create a graph showing land conversion between the years. I have generated cross tabulations between the years (2000-2010; 2010-2012) and I can create alluvial graphs for each of the tables. But how can I create a graph that contains all tree years and the transitions from 2000 to 2010 and 2012? I tried loading the cross tabulations as tables and converting to data frames but so far have had no luck.

**Comment by mbojan** [comment]
I think you should be able to do it. I'm not sure how your data look like. Can you provide some more detail or a small example?

**Comment by mbojan** [comment]
Would the following be similar to your setup?

Generate some data:

```r
library(dplyr)

set.seed(666)
N <- 1000
d <- data.frame( y2000 = sample(1:4, N, replace=TRUE) ) %>%
  mutate(
    y2010 = round(y2000 + runif(N, -1 ,1)),
    y2012 = round(y2010 + runif(N, -1, 1))
  ) %>%
  group_by(y2000, y2010, y2012) %>%
  summarise( freq = n() ) %>%
  as.data.frame()
```

looking like this

```
   y2000 y2010 y2012 freq
1      1     0    -1   19
2      1     0     0   28
3      1     0     1   11
4      1     1     0   36
5      1     1     1   71
6      1     1     2   34
7      1     2     1   21
8      1     2     2   27
9      1     2     3   16
10     2     1     0   12
11     2     1     1   27
12     2     1     2   14
13     2     2     1   36
14     2     2     2   64
15     2     2     3   28
16     2     3     2   12
17     2     3     3   31
18     2     3     4   15
19     3     2     1   16
20     3     2     2   29
21     3     2     3   16
22     3     3     2   24
23     3     3     3   68
24     3     3     4   34
25     3     4     3   12
26     3     4     4   33
27     3     4     5   20
28     4     3     2   13
29     4     3     3   23
30     4     3     4   17
31     4     4     3   29
32     4     4     4   67
33     4     4     5   37
34     4     5     4   12
35     4     5     5   29
36     4     5     6   19
```

so that every row is an area, `yXXX` variables decode land class (say 1=forest, 2=field etc.) which you then aggregate creating variable `freq` counting the number of areas with the respective landclass types in years 2000, 2010 and 2012.

Having such data you can use `alluvial` with, say:

```r
library(alluvial)

alluvial(d[,-4], freq=d$freq, 
         col=ifelse(d$y2010 == 2, "orange", "grey60"),
         alpha= 0.8
)
```

**Comment by dvictori** [comment]
Looking at your example I realized that the data frame I'm setting up is wrong and I'm not sure I have the necessary data to set it up. I have one table giving me the area of land cover change from 2000 to 2010, one with changes from 2010 to 2012 and another that gives the area changed from 2000 to 2012. That's because the GIS software I'm using tabulates area considering only two maps. I'm not sure I can use the data on these tables to come up with the area of change for each possible combination considering the three periods. Just in case, I've attached the data I'm using. Lines are the landuse classes of the earlier period and rows, of the latter. Meanwhile, I'll try another GIS software that will let me calculate the area of change considering the three periods.


[land_use_change_2000_2010_2012.zip](https://github.com/mbojan/alluvial/files/59253/land_use_change_2000_2010_2012.zip)

**Comment by mbojan** [comment]
For alluvial to work you essentially need a three-way cross-tabulation of the areas according to the land cover in years 2000-2010-2012. What you have, I think, are the three two-way marginal distributions of that three-way distribution, so it is not the same.

**Comment by dvictori** [comment]
I realized that now. Closing the issue.
