### ISSUE TITLE
local flow overlap orderings

### ISSUE THREAD

**Issue by corybrunson** [mbojan/alluvial#15]
The present version plots the alluvial flows in reverse order (so that those at the beginning of the order appear "on top"), according to each factor from left to right (using the calculation `rev(order(p$layer)[!hide])`). This can be seen in a non-transparent plot of all four Titanic variables:

``` r
alluvial(tit[,1:4], freq=tit$Freq, alpha=1, xw=0.2)
```

This convention uses the orders of the `levels()` of the factor variables, but it's not entirely determined by them; there are other possibilities. The present convention may be appropriate when the order of the variables in the data frame is important; though it may not be when the _adjacency_ of the variables is important. In that case, it would make more sense for those flows to be "on top" that connect two variable values that are first vectors). Both of these conventions, and maybe others, could be incorporated as special character inputs for the `layer` parameter.

**Comment by mbojan** [comment]
I'm not sure I understand what do you want to achieve. This is exactly what `layer` is for. You can modify the order in which the ribbons are plotted in any way you want.

**Comment by corybrunson** [comment]
I wasn't satisfied with my expression of it, either. But i think the key detail is that i'd like to control the *local* overlap order rather than the global, so that, if a flow is at the top of a factor in one column but at the bottom of one several columns away, then it can rise to the top nearer the one and sink to the bottom nearer the other. I'll see what i can do to realize this for myself, but maybe it's not a feature others would care for.

**Comment by mbojan** [comment]
OK, I got it. You mean modifing the plotting order of each of the ribbon **segments**.

This is related to a more general issue of specifying aesthetics to individual ribbon segments, for which I created a separate issue (#16).

I don't have a good, i.e. user-friendly, solution how to specify this. Ideas are welcome.
