### ISSUE TITLE
local flow placement order

### ISSUE THREAD

**Issue by corybrunson** [mbojan/alluvial#19]
This issue is similar to a previous one, "local flow overlap orderings", but has instead to do with the re-ordering of the data frame at each "pillar" of the diagram (which the ribbons connect). Currently this ordering is governed by the following line:

```r
a <- c(i, (1:ncol(d))[-i])
```

What this does, at each pillar `i`, is sort the rows of `d` according first to pillar `i`, and then to the remaining pillars in order from left to right. One aesthetic effect of this choice is that the ribbons often exhibit a great deal of overlap toward the right end of the diagram, since they are vertically sorted according to variables at the *left* end. Here is an example adapted from the package examples, where the ribbons connecting the `Age` and `Survived` pillars are unnecessarily entangled, given that each factor variable only has two levels:

```r
alluvial( tit[,1:4], freq=tit$Freq, border=NA )
```

My own experimenting led me to write a function to sort the data according to the columns in an order that begins with `i` and "zigzags" outward from there. It results in the diagram above exhibiting very little overlap on the right. But there may be better ways to handle this.

**Comment by mbojan** [comment]
I developed such a prototype of such a thing (I guess). Check branch `reordering`, argument `order`, also with an example in `examples/alluvial.R`.

**Comment by mbojan** [comment]
I am not sure if there is a better general solution for the order of ribbons. Now it is at least consistent. The degree of overlap depends on the variables (their ordering, how many values each has, etc.) and on the frequencies.

**Comment by corybrunson** [comment]
I'm reviewing how to view other branches; i gather that `clone` should have carried over all the branches from this repo, and indeed i see `sincurves` among those in my local folder. But i don't see an `ordering` branch, locally or here, nor does the `sincurves` branch have an `order` argument to `alluvial()`. Am i missing something less 101-level?

I do like the idea of having some control over how the ordering changes from pillar to pillar, without giving the user full control via some sort of matrix argument.

**Comment by mbojan** [comment]
Ah, I did not push it. Should be available now when you `git fetch`.

**Comment by corybrunson** [comment]
I'm curious too how best to do custom aesthetics; a full *n*(*k*-1) would certainly do it, but it would also be nice to have popular options, e.g. highlighting segments according to logical conditions (like `col` and `hide` now, but including variable name in order to subset segments).

Similarly, i see what you did with the `ordering` argument—the control is based on inputing a list of reordering vectors, rather than on choosing from among a set of available ordering functions (which is what i had in mind). Would it make sense to do something like i did with `blocks`, where the input could be either

* a character string for one of a set of local ordering functions (like `function(k,i) c(i, (1:k)[-i])`) or
* a vector or list of vectors giving the reordering sequence (or `NULL`), as in your example?

**Comment by corybrunson** [comment]
Now i think it's better to think of these as two dimensions of the process—the custom orderings control the "natural" order within each axis (or pillar), while the code i cited above controls the order in which the axes' orders are invoked. May i send a PR for the `reordering` branch that introduces a `rank.axes` argument, giving the user a few different options for the second?

**Comment by mbojan** [comment]
I should review the existing `reordering` code and rebase it. It will not happen until next week the soonest, I'm afraid.

Perhaps you work on your fork and we will integrate it once I clean-up the `reordering` branch?

I think through these features I am in for a more through rewrite of this function...

**Comment by corybrunson** [comment]
OK! Thanks, also for your guidance.

**Comment by mbojan** [comment]
Added in 46ef83125a16161831dda036996e8a736cd33f48
