### ISSUE TITLE
Adding numbers and "tie" weights

### ISSUE THREAD

**Issue by semenoffalex** [mbojan/alluvial#2]
Hi, Michał!

I've stumbled upon your blog post on alluvial diagramms:
http://bc.bojanorama.pl/2014/03/alluvial-diagrams/

The way you visualized them on the third picture reminded me a similar task, I need to solve.

I need to visualize the results of my project on regrouping students. In particular, I need to show the connections between "old" and "new" groups to demonstrate how many people from each of the "old" groups moved to each of the new groups. The only difference from your graph is that I want to show the numbers of people in groups (squares) and numbers on the lines ("ties"). 

Is it possible to modify you script for that purpose and how easy is it to do that?

**Comment by m-macaskill** [comment]
This would be an immensely useful enhancement, to build in this annotation capability directly within alluvial.

**Comment by mbojan** [comment]
Two years have passed, but we are getting there ;)

Other label placements should also be possible as now `alluvial` returns a lot of data that can be reused for adding additional plot elements.

``` r

library(alluvial)
d <- expand.grid(
  x=1:2,
  y=1:2
)
d$n <- 1:4
p <- alluvial(d[,-3], freq=d$n)
am <- p$alluvium_midpoints
for(i in seq(1, nrow(am))) {
  with(
    am[i,], {
      text(.x, .y, label=d$n[i], 
           adj=5,
           srt = atan(.slope) * 180 / pi
      )
      points(.x, .y)
    }
  )
}
```

![](http://i.imgur.com/51l6hiG.png)
