### ISSUE TITLE
Different `cex` and `cex.axis` for different labels / variables

### ISSUE THREAD

**Issue by aunz** [mbojan/alluvial#26]
The alluvial package is fantastic!
I notice that cex and cex.axis can be used to adjust font size for all labels. Is it possible to adjust font size for different columns. For example in the titanic example, cex = 1 for survial, cex = 0.5 for age, cex = 0.75 for Class

**Comment by mbojan** [comment]
Thanks. Unfortunately it is not possible at this moment.

For...

- `cex.axis` it is a single call to `axis` which does not accept different values for different ticks
- `cex` it is unfortunately embedded in a loop... :/ , implementing a vector input for it would be perhaps easier....

**Comment by mbojan** [comment]
Not feasible right now.
