### ISSUE TITLE
titles for alluvial()

### ISSUE THREAD

**Issue by corybrunson** [mbojan/alluvial#35]
The two functions plot their elements differently, and the `title` parameter is only available in `alluvial_ts()`. Is there a specific reason that titles haven't been implemented for `alluvial()`? I want to respond to [this question on SO](http://stackoverflow.com/questions/43130418/set-colors-title-in-an-alluvial-plot), and i was going to suggest using `mtext()` in tandem with the `ylim_offset` parameter. But it would be straightforward to add a `title` parameter (or maybe `main`, but that would be inconsistent with `alluvial_ts()`) and pass it to the `main` parameter in the `plot()` call, so i'm checking to see if that would be desirable. Sound good?

**Comment by mbojan** [comment]
Yeah... I did not implement `title` and so on exactly because this can be added with `mtext()`. I'd suggest extactly that. Making a space for a title would require adjusting `mar` argument (passed to `par()`). Tweaking the offsets should not be necessary.

A `title` argument could be added anyway though...

**Comment by mbojan** [comment]
I already started replying if it is OK with you.

**Comment by corybrunson** [comment]
Of course! Thanks for doing so.

Yeah, there's a slippery slope risk here, of adding more and more parameters from `plot()`, which is sometimes done using `...`. It makes sense to limit the plotting passes to the necessary ones; and, to me, that suggests that it's better to synchronize the functions by using `title`. If a `title` parameter is included, do you think the `mar` default should automatically change? (I'm playing with a "title" branch on my fork.)

**Comment by mbojan** [comment]
> Yeah, there's a slippery slope risk here, of adding more and more parameters from plot(), which is sometimes done using .... It makes sense to limit the plotting passes to the necessary ones; and, to me, that suggests that it's better to synchronize the functions by using title.

Yep, makes sense.

> If a title parameter is included, do you think the mar default should automatically change? (I'm playing with a "title" branch on my fork.)

The default `mar` (`2,1,1,1`) should accomodate a single-line title when `mtext` is used with `line=3`.

**Comment by corybrunson** [comment]
You're right! I thought i'd generated an example that showed inadequate space for the title, but it seems to work on the home examples. I'll send a PR momentarily.

**Comment by corybrunson** [comment]
Sorry, new etiquette question: I'm using a more recent version of Roxygen (6.0.1 versus 5.0.1), which results in other .Rd files being changed as well as "DESCRIPTION". Is that OK for a PR?

**Comment by mbojan** [comment]
> You're right! I thought i'd generated an example that showed inadequate space for the title, but it seems to work on the home examples. I'll send a PR momentarily.

Great, thanks.

> Sorry, new etiquette question: I'm using a more recent version of Roxygen (6.0.1 versus 5.0.1), which results in other .Rd files being changed as well as "DESCRIPTION". Is that OK for a PR?

Yes, go ahead.

**Comment by mbojan** [comment]
Done in #36
