### ISSUE TITLE
Ending an alluvia if all subsequent element values are NA

### ISSUE THREAD

**Issue by axellecb** [mbojan/alluvial#44]
Would it be possible to add a functionality where the alluvia come to a hard stop if there are only NA values for the remaining elements, or skip and element if its value is NA? 

Here is an example of the chart I am building: 
![alluvial test](https://user-images.githubusercontent.com/10040180/28531621-64d94b80-7065-11e7-9615-8fdbad65aa30.png)

In my original data set, I had NA values instead of zeros for each of the last three axes (Rating Y1, Y2 and Y3), indicating either subject exit or non entry (i.e. if entry Year is Y3, the value for Rating_Y1 and Rating Y_2 should be NA. 

However, I get the following error message: Error in if (mx == 0) mx <- 1 : missing value where TRUE/FALSE needed. Below is an example of what I had in mine using the d3 Sankey HTML widget, in which the flows skip a node if no value is given for that node. 

![image](https://user-images.githubusercontent.com/10040180/28531910-3679fba8-7066-11e7-8ede-b7f7a91838eb.png)

And another example where flows come to a hard stop if all subsequent node values are NA

http://blog.insightdatalabs.com/content/images/2015/10/Screenshot-2015-10-29-17-16-40-1.png
![image](https://user-images.githubusercontent.com/10040180/28532066-b0b319a4-7066-11e7-8e11-f963c57a0d91.png)

**Comment by mbojan** [comment]
I am afraid this will be impossible with `alluvial` as is. What you are trying to achieve is no longer an  alluvial diagram strictly speaking.

@corybrunson is this feasible with your ggplot2 implementation?

I think your best shot would be to use one of the R packages for sankey diagrams, or `riverplot`.

**Comment by corybrunson** [comment]
@mbojan not in the way that @axellecb has in mind, i think. It is possible in **ggalluvial** to omit flows between the axes when values are `NA`:
```r
library(ggalluvial)
data(majors)
majors$curriculum <- as.factor(majors$curriculum)
ggplot(majors,
       aes(x = semester, stratum = curriculum, alluvium = student,
           label = curriculum)) +
  geom_alluvium(fill = "darkgrey", na.rm = TRUE) +
  geom_stratum(aes(fill = curriculum), color = NA, na.rm = TRUE) +
  theme_bw()
```
I just realized that there's no illustration of this in the examples, so i'll include one now. Thanks!

**Comment by axellecb** [comment]
Thank you both for your answers. I am playing around with gg alluvial currently. 

I know what I am trying to achieve is not strictly an alluvial diagram, but I was hoping to marry the granularity of an alluvial diagram with the fluidity of the Sankey. So far, I've struggled to find a package/function/graph that would be the equivalent of a Sankey but with the ability to track a group from beginning to end without aggregation come the first node. That functionality is what I really appreciated about your package. Any suggestions would be welcome !
