### ISSUE TITLE
Minimizing alluvial crossing

### ISSUE THREAD

**Issue by mmaresch** [mbojan/alluvial#45]
@mbojan 
Hello,
I was using your package and I was wondering if you developed a function to order the alluvials in a way that minimizes their crossing ? Perhaps through the use of a cost function ?
I tried to order my data using the "ordering" parameter, but I had no luck.

Thanks for you help !

**Comment by mbojan** [comment]
I did not. I usually have data in which all combinations of values of plotted variables have non-zero frequencies. My personal view is that very little can be gained by fiddling with ordering to minimize crossings. The default ordering which is based on alphanumerical ordering of "levels" on each variable makes the plot IMHO easier to read.

Nevertheless, I believe @corybrunson played with idea of minimizing crossings when developing https://github.com/corybrunson/ggalluvial .

**Comment by corybrunson** [comment]
Thanks for the shout-out. : ) That sums it up pretty well. I'm not actively experimenting with this feature right now, and initial attempts didn't produce dramatic improvements in the appearance of the diagrams. For most purposes, i tend to agree that it makes more sense to arrange the strata according to their innate order (if they are factor variables), or else just alphabetically. Though, as @mbojan suggests, it might be useful for high-dimensional sparse data, i.e. many strata and many combinations of them with zero frequencies.

**Comment by mmaresch** [comment]
Thank you so much for your responses !
