### ISSUE TITLE
Bug in the alluvial source code when trying to set the margins

### ISSUE THREAD

**Issue by DavidSriker** [mbojan/alluvial#46]
When one tried to set the margin of the `alluvial` plot using `par(mar=c(4,4,4,4))` nothing happened.

After looking at the source code I've noticed that you hardcoded set the `par(mar=c(2,1,1,1))` and overwrite any margin setting outside the function.

I suggest adding an option to the function to get a margin input `mar_in` and replace:
`par(mar=c(2,1,1,1))` 
with:
`par(mar=mar_in)`

**Comment by mbojan** [comment]
Thanks @DavidSriker , it has been requested in #30. The dev version on GitHub exposes `mar` argument  (implemented in dffa0cc7d9b787c9aaeb77fdcbd83f02704c4833). Use `remotes::install_github` to install the package directly from GH.
