### ISSUE TITLE
the plot does not obey par

### ISSUE THREAD

**Issue by coquito77** [mbojan/alluvial#47]
The alluvial function has a line `op <- par(mar = c(2, 1, 1, 1))` that makes it hard to place titles on the plot, see below,

`       

    tit <- as.data.frame(Titanic)

    # 2d
    tit2d <- aggregate( Freq ~ Class + Survived, data=tit, sum)

    par(mar = c(5.1, 4.1, 1.1, 8.1))

    alluvial::alluvial( tit2d[,1:2], freq=tit2d$Freq, xw=0.0, alpha=0.8,
         gap.width=0.1, col= "steelblue", border="white",
         layer = tit2d$Survived != "Yes" )

    title("A nice title"
      ,xlab  = "something at the bottom")

    myalluvial <- alluvial::alluvial

    # remove op references
    body(myalluvial)[[21]]

    body(myalluvial)[[28]]

    body(myalluvial) <- body(myalluvial)[-21]

    body(myalluvial) <- body(myalluvial)[-27]

    body(myalluvial)[[21]]

     # try again with updated function
    par(mar = c(5.1, 4.1, 1.1, 8.1))

    myalluvial( tit2d[,1:2], freq=tit2d$Freq, xw=0.0, alpha=0.8,
         gap.width=0.1, col= "steelblue", border="white",
         layer = tit2d$Survived != "Yes" )

    title("A nice title"
      ,xlab  = "something at the bottom")

`

**Comment by mbojan** [comment]
Argument `mar` is now exposed because of #31 in the dev version (not yet on CRAN). Please install from GitHub.
