### ISSUE TITLE
ENH: Optionally assign axis labels from a source other than dataframe column names

### ISSUE THREAD

**Issue by m-macaskill** [mbojan/alluvial#9]
Currently, axis labels come from the names of the relevant columns in the source dataframe. This works fine for the Titanic dataset, where the column names are just single words. But this default naming scheme seems to restrict labels to values which are valid R variable names. In particular, it doesn't allow  labels to be several words, separated by spaces. 

But fundamentally, alluvial is a great package: a single function produces great output as is. Happy to tweak it afterwards in a drawing program, but it would be nice to build in a bit more labelling flexibility.

**Comment by mbojan** [comment]
good idea
